In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# WE can randomly reorder (permutate) a Series, or the rows in a DataFrame

#Let's take a look
dframe = DataFrame(np.arange(4 * 4).reshape((4, 4)))

#Create an array with a random perumation of 0,1,2,3
blender = np.random.permutation(4)

blender

array([0, 1, 3, 2])

In [3]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [4]:
# Now permutate the dframe based on the blender
dframe.take(blender)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11

In [5]:
# Now what if we want permuations WITH replacement

In [6]:
# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3
box = np.array([1,2,3])

# Now lets create a random permuation WITH replacement using randint
shaker = np.random.randint(0, len(box), size=10)

In [7]:
# Let's check teh box "shaker"
shaker

array([1, 2, 2, 1, 0, 1, 0, 1, 1, 1])

In [8]:
#Now lets grab form the box
hand_grabs = box.take(shaker)

#show
hand_grabs

array([2, 3, 3, 2, 1, 2, 1, 2, 2, 2])

Congratulations! We're all done with this Section.
Up next: Working with Data Part 3 !!!