In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([ 0.01335604,  0.83884297, -0.11221248,  0.61779838, -0.92812881,
        2.00565974,  0.06532123,  0.08086312, -1.86230571, -1.62372299])

In [6]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([ 1.95922019, -1.60911845, -0.96564873, -1.00408402,  1.63492591,
       -1.55303136, -0.28447716,  0.11232442,  0.24212681, -1.14373685])

In [7]:
#Addition
np.add(A,B)

array([ 1.97257624, -0.77027548, -1.0778612 , -0.38628564,  0.7067971 ,
        0.45262838, -0.21915593,  0.19318754, -1.6201789 , -2.76745984])

In [8]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 1.95922019,  0.83884297, -0.11221248,  0.61779838,  1.63492591,
        2.00565974,  0.06532123,  0.11232442,  0.24212681, -1.14373685])

In [9]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

False